# Generated by Django 4.2.3 on 2023-11-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0004_alter_pick_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_self',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
