# Generated by Django 4.2.3 on 2023-11-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0005_participant_is_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1_score',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_score',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
