# Generated by Django 4.2.3 on 2023-12-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0006_game_team1_score_game_team2_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team1_score',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Team 1 Score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team2_score',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Team 2 Score'),
        ),
    ]
