# Generated by Django 4.2.3 on 2023-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0007_alter_game_team1_score_alter_game_team2_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
